###
### A complete description of a Prefect Deployment for flow 'ghcndToGcsBqFlow'
###
name: docker-deployment
description: null
version: 2e70b7afae974fa91641e753d0dc0249
# The work queue that will handle this deployment's runs
work_queue_name: default
work_pool_name: null
tags:
- test
parameters: {"years": [2017]}
schedule: null
is_schedule_active: null
infra_overrides: {}
infrastructure:
  type: docker-container
  env: {
    GCLOUD_PROJECT_ID: "data-pipeline-396809",
    GCS_BUCKET_NAME: "noaa_ghcn_data_lake_data-pipeline-396809",
    GCS_TEMP_BUCKET_NAME: "dataproc-temp-asia-southeast1-663749668341-9a8yqovx",
    BQ_DATASET: "noaa_ghcn_all"
  }
  labels: {}
  name: null
  command: null
  image: noaa:test2
  image_pull_policy: null
  image_registry: null
  networks: []
  network_mode: null
  auto_remove: false
  volumes: ['/Users/admin/Downloads/data-pipeline-396809-583622d42f37.json:/app/lib/gcloud_creds.json']
  stream_output: true
  memswap_limit: null
  mem_limit: null
  privileged: false
  block_type_slug: docker-container
  _block_type_slug: docker-container

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: ghcndToGcsBqFlow
manifest_path: null
storage: null
path: /opt/prefect/flows
entrypoint: ghcnd_to_gcs_bq.py:ghcndToGcsBqFlow
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    years:
      title: years
      default:
      - 2020
      - 2021
      - 2022
      - 2023
      position: 0
    countryCode:
      title: countryCode
      default: VM
      position: 1
  required: null
  definitions: null
timestamp: '2023-08-21T06:47:52.594325+00:00'
triggers: []
